### ISSUE TITLE
Bug: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by viveknigam3003** [dannyconnell/localbase#34]
## Motivation
When trying to use `localbase` with my NextJS application, the app compiles successfully but shows an error in the terminal when refreshing the browser.

```
\node_modules\localbase\index.js:1
import Localbase from './localbase/localbase'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Configuration:**
localbase: ^0.7.5
next: 10.1.3
react: 17.0.2

## Modification
Making the library compactible with for working with Next.js

**Comment by viveknigam3003** [comment]
> Hello!!.... Did you found any way to use it in next.js ?

@MdYeasinSamadArnob no I didn't. I switched to local storage instead 😅

**Comment by mutqiamrillah** [comment]
same issue!

**Comment by bielmarfran** [comment]
Hi, I was having the same problem, having found other packages with the same issue with Next, the recommended solution was to install the 'next-transpile-modules' package and change some edits to the next.config.

    //Inside your next.config.js
    const withTM = require('next-transpile-modules')(['localbase']) // pass the modules you would like to see transpiled
    module.exports = withTM()

My current use of the Localbase is dead simple, so I didn't really test a lot of the functionality, but everything should work normally.

**Comment by Javadyakuza** [comment]
> 

 <script src="https://unpkg.com/localbase/dist/localbase.dev.js"></script>
     <script src="./localbase.js"></script>
use the first script tag instead of installing npm and stuff
and use the second script tag as your own js file to write your codes

**Comment by AntonLie** [comment]
same issue

**Comment by fullupe** [comment]
> Hi, I was having the same problem, having found other packages with the same issue with Next, the recommended solution was to install the 'next-transpile-modules' package and change some edits to the next.config.
> 
> ```
> //Inside your next.config.js
> const withTM = require('next-transpile-modules')(['localbase']) // pass the modules you would like to see transpiled
> module.exports = withTM()
> ```
> 
> My current use of the Localbase is dead simple, so I didn't really test a lot of the functionality, but everything should work normally.
nice worked 👍...but add() overwrite after refresh ...any fix ?

**Comment by rookasrudzianskas** [comment]
> This solution is correct, you have to install the 'next-transpile-modules' package via npm or yarn and modify next.config.

`// Modify project next.config.js
const withTM = require('next-transpile-modules')(['localbase']) // pass the modules you would like to see transpiled
module.exports = withTM()`

Tested it in more complicated environment, everything works smoothly 🚀

**Comment by the-alchemist-gh** [comment]
Hello, Did you find any fix for this Issue?

**Comment by BasilArackal** [comment]
> const withTM = require('next-transpile-modules')(['localbase']) // pass the modules you would like to see transpiled
> module.exports = withTM()

With Next.js 13 or Above the syntax is as follows 👍 

>const nextConfig = {
> ...
>  transpilePackages: ["localbase"],
> };
>
> module.exports = nextConfig;
